language: python
python:
  - "3.8"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - sudo pip3.8 install --user -r requirements.txt
script:
  - pytest --cov-report term --cov=equilibrium
after_success:
  - codecov