version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./equilibrium/server/Dockerfile
      args:
        host: "0.0.0.0"
        port: "8000"
        url: "rabbitmq://rabbitmq:5672"
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
  rabbitmq:
    image: "rabbitmq"
    expose:
      - "5672"